In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from shadowroutes.config import settings

src_path = Path('../')
os.chdir(src_path)

## Parameters

In [17]:
# Safety and institutional performance perception (ENVIPE 2025 - INEGI) - obtained in November 2025
envipe_path = Path(settings.DATA_ROOT / 'envipe-inegi' / 'raw' / 'conjunto_de_datos_envipe_2025_csv' / 'tper_vic1_envipe2025' / 'conjunto_de_datos' / 'conjunto_de_datos_tper_vic1_envipe2025.csv')
dict_envipe_path = Path(settings.DATA_ROOT / 'envipe-inegi' / 'raw' / 'conjunto_de_datos_envipe_2025_csv' / 'tper_vic1_envipe2025' / 'diccionario_de_datos' / 'diccionario_de_datos_tper_vic1_envipe2025.csv')

# Population estimates (mid-year) from CONAPO - obtained in October 2025
data_path_pop_m = Path(settings.DATA_ROOT / 'conapo' / 'raw' / 'pobproy_quinq1.csv')

# Output path
out_collusion_panel = Path(settings.DATA_ROOT / 'processed' / 'collusion_index_panel.csv')

## Data

In [3]:
# Loads data related to personnel in police corporations
df_envipe = pd.read_csv(envipe_path, encoding='utf-8', dtype={"CVE_ENT": str, "CVE_MUN": str})
print(f'File read: {print(envipe_path.name)}')

print(df_envipe.shape)
df_envipe.head()

conjunto_de_datos_tper_vic1_envipe2025.csv
File read: None
(91182, 240)

,ID_VIV,ID_HOG,ID_PER,UPM,VIV_SEL,HOGAR,RESUL_H,R_SEL,SEXO,EDAD,...,AP5_8_11_5,AP5_9,FAC_HOG,FAC_ELE,FAC_HOG_AM,FAC_ELE_AM,DOMINIO,ESTRATO,EST_DIS,UPM_DIS
0,100107.01,0100107.01.01,0100107.01.01.01,100107,1,1,B,1,2,56,...,NaN,3,241,241,241.0,241.0,U,2,1,47
1,100107.02,0100107.02.01,0100107.02.01.02,100107,2,1,A,2,2,30,...,9.0,2,241,482,241.0,482.0,U,2,1,47
2,100107.03,0100107.03.01,0100107.03.01.04,100107,3,1,B,4,2,18,...,NaN,9,241,963,241.0,963.0,U,2,1,47
3,100107.04,0100107.04.01,0100107.04.01.03,100107,4,1,A,3,1,22,...,9.0,2,241,723,241.0,723.0,U,2,1,47
4,100107.05,0100107.05.01,0100107.05.01.01,100107,5,1,B,1,2,36,...,NaN,2,241,482,241.0,482.0,U,2,1,47

In [4]:
df_envipe.CVE_MUN.unique()

array(['001', '002', '003', '005', '006', '007', '010', '011', '004',
       '008', '009', '012', '017', '018', '020', '022', '024', '025',
       '027', '028', '030', '032', '033', '035', '036', '014', '015',
       '019', '023', '040', '043', '047', '048', '052', '059', '061',
       '065', '068', '071', '074', '078', '079', '083', '087', '089',
       '094', '096', '097', '099', '101', '102', '106', '108', '110',
       '111', '112', '124', '081', '016', '021', '031', '037', '041',
       '044', '051', '062', '064', '067', '069', '072', '077', '084',
       '090', '093', '100', '109', '114', '115', '045', '050', '055',
       '013', '026', '029', '038', '039', '042', '046', '053', '056',
       '057', '066', '075', '058', '063', '076', '082', '049', '054',
       '073', '080', '070', '085', '098', '103', '120', '034', '125',
       '060', '091', '092', '095', '104', '118', '121', '122', '086',
       '088', '107', '126', '143', '150', '157', '166', '177', '184',
       '190', '197', '198', '227', '248', '293', '298', '309', '310',
       '324', '338', '342', '350', '367', '375', '385', '390', '397',
       '399', '401', '403', '409', '439', '469', '505', '515', '539',
       '545', '551', '557', '560', '565', '570', '130', '134', '139',
       '170', '202', '203', '205', '207', '247', '271', '278', '313',
       '326', '330', '334', '377', '379', '412', '417', '427', '428',
       '434', '458', '462', '468', '478', '482', '516', '517', '520',
       '527', '549', '567', '117', '119', '132', '136', '138', '140',
       '142', '148', '149', '154', '156', '162', '164', '169', '179',
       '180', '208', '217', '153', '155', '167', '172', '189', '194',
       '200', '174', '105', '116', '123', '127', '128', '131', '133',
       '135', '141', '147', '158', '175', '178', '182', '191', '193',
       '199', '204', '160', '192', '201'], dtype=object)

In [5]:
# Loads data related to personnel in police corporations
df_envipe_dict = pd.read_csv(dict_envipe_path, encoding='utf-8')
print(f'File read: {print(dict_envipe_path.name)}')

print(df_envipe_dict.shape)
df_envipe_dict.head()

diccionario_de_datos_tper_vic1_envipe2025.csv
File read: None
(903, 5)

,NOMBRE_CAMPO,NEMONICO,TIPO,LONGITUD,RANGO_CLAVES
0,Identificador de vivienda seleccionada,ID_VIV,Alfanumérico,10,"0100001.01,…,3299999.99"
1,Identificador del hogar seleccionado,ID_HOG,Alfanumérico,13,"0100001.01.01,…,3299999.99.99"
2,Identificador del informante seleccionado,ID_PER,Alfanumérico,16,"0100001.01.01.01,…,3299999.99.99.30"
3,Control de vivienda (UPM),UPM,Carácter,7,"0100001,…,3299999"
4,Vivienda seleccionada,VIV_SEL,Carácter,2,"01,…,99"

In [6]:
dict_vars = dict(zip(df_envipe_dict["NEMONICO"], df_envipe_dict["NOMBRE_CAMPO"], strict=False))
dict_vars

{'ID_VIV': 'Identificador de vivienda seleccionada',
 'ID_HOG': 'Identificador del hogar seleccionado',
 'ID_PER': 'Identificador del informante seleccionado',
 'UPM': 'Control de vivienda (UPM)',
 'VIV_SEL': 'Vivienda seleccionada',
 'HOGAR': 'Control del hogar',
 'RESUL_H': 'Resultado de la visita al hogar',
 'R_SEL': 'Número de renglón de la persona seleccionada',
 'SEXO': 'Sexo',
 'EDAD': 'Edad',
 'AREAM': 'Área Urbana de Interés',
 'CVE_ENT': 'Clave Entidad',
 'NOM_ENT': 'Nombre de la Entidad',
 'CVE_MUN': 'Municipio',
 'NOM_MUN': 'Nombre del municipio',
 'AP4_1': 'Tiempo habitando en la vivienda',
 'AP4_2_01': 'Temas que más preocupan: pobreza',
 'AP4_2_02': 'Temas que más preocupan: desempleo',
 'AP4_2_03': 'Temas que más preocupan: narcotráfico',
 'AP4_2_04': 'Temas que más preocupan: aumento de precios',
 'AP4_2_05': 'Temas que más preocupan: inseguridad',
 'AP4_2_06': 'Temas que más preocupan: desastres naturales',
 'AP4_2_07': 'Temas que más preocupan: escasez de agua',
 'AP4_2_08': 'Temas que más preocupan: corrupción',
 'AP4_2_09': 'Temas que más preocupan: educación',
 'AP4_2_10': 'Temas que más preocupan: salud',
 'AP4_2_11': 'Temas que más preocupan: falta de castigo a los delincuentes',
 'AP4_2_12': 'Temas que más preocupan: otro',
 'AP4_2_13': 'Temas que más preocupan: ninguno',
 'AP4_2_99': 'Temas que más preocupan: no especificado',
 'AP4_3_1': 'Percepción sobre seguridad en su colonia o localidad',
 'AP4_3_2': 'Percepción sobre seguridad en su municipio o demarcación territorial',
 'AP4_3_3': 'Percepción sobre seguridad en su estado',
 'AP4_4_01': 'Percepción sobre seguridad en su casa',
 'AP4_4_02': 'Percepción sobre seguridad en su trabajo',
 'AP4_4_03': 'Percepción sobre seguridad en la calle',
 'AP4_4_04': 'Percepción sobre seguridad en la escuela',
 'AP4_4_05': 'Percepción sobre seguridad en el mercado',
 'AP4_4_06': 'Percepción sobre seguridad en el centro comercial',
 'AP4_4_07': 'Percepción sobre seguridad en el banco',
 'AP4_4_08': 'Percepción sobre seguridad en el cajero automático localizado en la vía pública',
 'AP4_4_09': 'Percepción sobre seguridad en el transporte público',
 'AP4_4_10': 'Percepción sobre seguridad en el automóvil ',
 'AP4_4_11': 'Percepción sobre seguridad en la carretera',
 'AP4_4_12': 'Percepción sobre seguridad en el parque o centro recreativo ',
 'AP4_4_A': 'Percepción sobre seguridad al caminar solo(a) por la noche en los alrededores de su vivienda',
 'AP4_5_01': 'Incivilidades en su colonia: consumo de alcohol en la calle',
 'AP4_5_02': 'Incivilidades en su colonia: pandillerismo o bandas violentas',
 'AP4_5_03': 'Incivilidades en su colonia: riñas entre vecinos(as)',
 'AP4_5_04': 'Incivilidades en su colonia: venta ilegal de alcohol',
 'AP4_5_05': 'Incivilidades en su colonia: venta de productos piratas',
 'AP4_5_06': 'Incivilidades en su colonia: violencia policiaca contra ciudadanos(as)',
 'AP4_5_07': 'Incivilidades en su colonia: invasión de predios',
 'AP4_5_08': 'Incivilidades en su colonia: consumo de droga',
 'AP4_5_09': 'Incivilidades en su colonia: robos o asaltos frecuentes',
 'AP4_5_10': 'Incivilidades en su colonia: venta de droga',
 'AP4_5_11': 'Incivilidades en su colonia: disparos frecuentes',
 'AP4_5_12': 'Incivilidades en su colonia: prostitución',
 'AP4_5_13': 'Incivilidades en su colonia: secuestros',
 'AP4_5_14': 'Incivilidades en su colonia: homicidios',
 'AP4_5_15': 'Incivilidades en su colonia: extorsiones (cobro de piso)',
 'AP4_5_16': 'Incivilidades en su colonia: robo o venta ilegal de gasolina o diésel (huachicol)',
 'AP4_5_17': 'Incivilidades en su colonia: tomas irregulares de luz(energía eléctrica) o diablitos',
 'AP4_5_18': 'Incivilidades en su colonia: ninguna',
 'AP4_5_99': 'Incivilidades en su colonia: no especificado',
 'AP4_6_1': 'Sensación de ser víctima de robo o asalto en la calle o transporte público',
 'AP4_6_2': 'Sensación de ser víctima de lesiones por agresión física',
 'AP4_6_3': 'Sensación de ser víctima de extorsión o secuestro',
 'AP4_7_1': 'Percepción sobre tendencia de seguridad pública en su colonia o localidad',
 'AP4_7_2': 'Percepción sobre tendencia de seguridad pública en su estado',
 'AP4_7_3': 'Percepción sobre tendencia de seguridad pública en su país',
 'AP4_8_1': 'Problemas en su colonia: falta de alumbrado público',
 'AP4_9_1': 'Capacidad de organización para resolver falta de alumbrado',
 'AP4_8_2': 'Problemas en su colonia: falta de agua',
 'AP4_9_2': 'Capacidad de organización para resolver falta de agua',
 'AP4_8_3': 'Problemas en su colonia: baches o fugas de agua',
 'AP4_9_3': 'Capacidad de organización para resolver baches o fugas de agua',
 'AP4_8_4': 'Problemas en su colonia: pandillerismo violento',
 'AP4_9_4': 'Capacidad de organización para resolver pandillerismo violento ',
 'AP4_8_5': 'Problemas en su colonia: robos',
 'AP4_9_5': 'Capacidad de organización para resolver robos',
 'AP4_8_6': 'Problemas en su colonia: delincuencia en alrededores de escuelas',
 'AP4_9_6': 'Capacidad de organización para resolver delincuencia en alrededores de escuelas',
 'AP4_10_01': 'Dejar de salir de noche por temor a ser víctima',
 'AP4_10_02': 'Dejar de permitir a menores salir solos(as) por temor a ser víctima',
 'AP4_10_03': 'Dejar de visitar parientes o amigos(as) por temor a ser víctima',
 'AP4_10_04': 'Dejar de tomar taxi por temor a ser víctima',
 'AP4_10_05': 'Dejar de usar transporte público por temor a ser víctima',
 'AP4_10_06': 'Dejar de llevar dinero en efectivo por temor a ser víctima',
 'AP4_10_07': 'Dejar de ir a la escuela por temor a ser víctima',
 'AP4_10_08': 'Dejar de ir al cine o teatro por temor a ser víctima',
 'AP4_10_09': 'Dejar de salir a caminar por temor a ser víctima',
 'AP4_10_10': 'Dejar de usar joyas por temor a ser víctima',
 'AP4_10_11': 'Dejar de salir a comer o cenar por temor a ser víctima',
 'AP4_10_12': 'Dejar de llevar tarjeta de crédito o débito por temor a ser víctima',
 'AP4_10_13': 'Dejar de ir al estadio por temor a ser víctima',
 'AP4_10_14': 'Dejar de frecuentar centros comerciales por temor a ser víctima',
 'AP4_10_15': 'Dejar de viajar por carretera por temor a ser víctima',
 'AP4_10_16': 'Dejar de llevar teléfono móvil o celular por temor a ser víctima',
 'AP4_11_01': 'Medidas de protección contra delincuencia: cambiar o reforzar puertas o ventanas',
 'AP4_11_02': 'Medidas de protección contra delincuencia: cambiar, colocar o reforzar cerraduras y/o candados',
 'AP4_11_03': 'Medidas de protección contra delincuencia: colocar o reforzar rejas o bardas',
 'AP4_11_04': 'Medidas de protección contra delincuencia: instalar alarmas y/o videocámaras de vigilancia',
 'AP4_11_05': 'Medidas de protección contra delincuencia: contratar vigilancia privada en la calle o colonia',
 'AP4_11_06': 'Medidas de protección contra delincuencia: realizar acciones conjuntas con sus vecinos(as)',
 'AP4_11_07': 'Medidas de protección contra delincuencia: contratar seguros',
 'AP4_11_08': 'Medidas de protección contra delincuencia: comprar un perro guardián',
 'AP4_11_09': 'Medidas de protección contra delincuencia: adquirir armas de fuego',
 'AP4_11_10': 'Medidas de protección contra delincuencia: cambiarse de vivienda o lugar de residencia',
 'AP4_11_11': 'Medidas de protección contra delincuencia: Otra medida',
 'AP4_12': 'Gastos en protección contra delincuencia',
 'AP5_1_01': 'Acciones en municipio/localidad: construcción/mantenimiento parques y canchas deportivas',
 'AP5_1_02': 'Acciones en municipio/localidad: mejorar el alumbrado',
 'AP5_1_03': 'Acciones en municipio/localidad: mejora de ingreso',
 'AP5_1_04': 'Acciones en municipio/localidad: atender desempleo',
 'AP5_1_05': 'Acciones en municipio/localidad: atención a jóvenes para reducir delincuencia',
 'AP5_1_06': 'Acciones en municipio/localidad: organización de vecinos(as) para contratar seguridad privada',
 'AP5_1_07': 'Acciones en municipio/localidad: policía de barrio',
 'AP5_1_08': 'Acciones en municipio/localidad: operativos contra la delincuencia',
 'AP5_1_09': 'Acciones en municipio/localidad: programas de sensibilización a denunciar',
 'AP5_1_10': 'Acciones en municipio/localidad: mayor patrullaje',
 'AP5_1_11': 'Acciones en municipio/localidad: combatir corrupción',
 'AP5_1_12': 'Acciones en municipio/localidad: combatir narcotráfico',
 'AP5_1_13': 'Acciones en municipio/localidad: actividades o programas para prevenir la violencia y/o la delincuencia',
 'AP5_1_14': 'Acciones en municipio/localidad: otra',
 'AP5_2_1': 'Confianza en vecinos(as)',
 'AP5_2_2': 'Confianza en compañeros(as) de trabajo/negocio, escuela',
 'AP5_2_3': 'Confianza en familiares o parientes',
 'AP5_2_4': 'Confianza en amigos(as)',
 'AP5_3_01': 'Identificación de Policía de Tránsito Municipal',
 'AP5_3_02': 'Identificación de Policía Preventiva Municipal',
 'AP5_3_03': 'Identificación de Policía Estatal',
 'AP5_3_04': 'Identificación de Guardia Nacional',
 'AP5_3_05': 'Identificación de Policía Ministerial, Judicial o de Investigación',
 'AP5_3_06': 'Identificación del Ministerio Público (MP) y Fiscalías Estatales',
 'AP5_3_07': 'Identificación de la Fiscalía General de la República (FGR)',
 'AP5_3_08': 'Identificación del Ejército',
 'AP5_3_09': 'Identificación de la Fuerza Aérea Mexicana',
 'AP5_3_10': 'Identificación de la Marina',
 'AP5_3_11': 'Identificación de jueces',
 'AP5_4_01': 'Confianza en Policía de Tránsito Municipal',
 'AP5_5_01': 'Percepción sobre corrupción de Policía de Tránsito Municipal',
 'AP5_6_01': 'Percepción sobre desempeño de Policía de Tránsito Municipal',
 'AP5_7_1': 'Disposición de Policía de Tránsito Municipal',
 'AP5_4_02': 'Confianza en Policía Preventiva Municipal',
 'AP5_5_02': 'Percepción sobre corrupción de Policía Preventiva Municipal',
 'AP5_6_02': 'Percepción sobre desempeño de Policía Preventiva Municipal',
 'AP5_7_2': 'Disposición de Policía Preventiva Municipal',
 'AP5_4_03': 'Confianza en Policía Estatal',
 'AP5_5_03': 'Percepción sobre corrupción de Policía Estatal',
 'AP5_6_03': 'Percepción sobre desempeño de Policía Estatal',
 'AP5_7_3': 'Disposición de Policía Estatal',
 'AP5_4_04': 'Confianza en Guardia Nacional',
 'AP5_5_04': 'Percepción sobre corrupción de Guardia Nacional',
 'AP5_6_04': 'Percepción sobre desempeño de Guardia Nacional',
 'AP5_7_4': 'Disposición de Guardia Nacional',
 'AP5_4_05': 'Confianza en Policía Ministerial, Judicial o de Investigación',
 'AP5_5_05': 'Percepción sobre corrupción de Policía Ministerial, Judicial o de Investigación',
 'AP5_6_05': 'Percepción sobre desempeño de Policía Ministerial, Judicial o de Investigación',
 'AP5_4_06': 'Confianza en Ministerio Público (MP) y Fiscalías Estatales',
 'AP5_5_06': 'Percepción sobre corrupción de Ministerio Público (MP) y Fiscalías Estatales',
 'AP5_6_06': 'Percepción sobre desempeño de Ministerio Público (MP) y Fiscalías Estatales',
 'AP5_4_07': 'Confianza en Fiscalía General de la República (FGR)',
 'AP5_5_07': 'Percepción sobre corrupción de Fiscalía General de la República (FGR)',
 'AP5_6_07': 'Percepción sobre desempeño de Fiscalía General de la República (FGR)',
 'AP5_4_08': 'Confianza en Ejército',
 'AP5_5_08': 'Percepción sobre corrupción del Ejército',
 'AP5_6_08': 'Percepción sobre desempeño del Ejército',
 'AP5_4_09': 'Confianza en Fuerza Aérea Mexicana',
 'AP5_5_09': 'Percepción sobre corrupción de Fuerza Aérea Mexicana',
 'AP5_6_09': 'Percepción sobre desempeño de Fuerza Aérea Mexicana',
 'AP5_4_10': 'Confianza en Marina',
 'AP5_5_10': 'Percepción sobre corrupción de la Marina',
 'AP5_6_10': 'Percepción sobre desempeño de la Marina',
 'AP5_4_11': 'Confianza en jueces',
 'AP5_5_11': 'Percepción sobre corrupción de jueces',
 'AP5_6_11': 'Percepción sobre desempeño de jueces',
 'AP5_8_01_1': 'Identificación de Policía de Tránsito Municipal por contacto directo.',
 'AP5_8_01_2': 'Identificación de Policía de Tránsito Municipal porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_01_3': 'Identificación de Policía de Tránsito Municipal porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_01_4': 'Identificación de Policía de Tránsito Municipal porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_01_5': 'Identificación de Policía de Tránsito Municipal. Otro',
 'AP5_8_02_1': 'Identificación de Policía Preventiva Municipal por contacto directo.',
 'AP5_8_02_2': 'Identificación de Policía Preventiva Municipal porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_02_3': 'Identificación de Policía Preventiva Municipal porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_02_4': 'Identificación de Policía Preventiva Municipal porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_02_5': 'Identificación de Policía Preventiva Municipal. Otro',
 'AP5_8_03_1': 'Identificación de Policía Estatal por contacto directo.',
 'AP5_8_03_2': 'Identificación de Policía Estatal porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_03_3': 'Identificación de Policía Estatal porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_03_4': 'Identificación de Policía Estatal porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_03_5': 'Identificación de Policía Estatal. Otro',
 'AP5_8_04_1': 'Identificación de Guardia Nacional por contacto directo.',
 'AP5_8_04_2': 'Identificación de Guardia Nacional porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_04_3': 'Identificación de Guardia Nacional porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_04_4': 'Identificación de Guardia Nacional porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_04_5': 'Identificación de Guardia Nacional. Otro',
 'AP5_8_05_1': 'Identificación de Policía Ministerial, Judicial o de Investigación por contacto directo.',
 'AP5_8_05_2': 'Identificación de Policía Ministerial, Judicial o de Investigación porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_05_3': 'Identificación de Policía Ministerial, Judicial o de Investigación porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_05_4': 'Identificación de Policía Ministerial, Judicial o de Investigación porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_05_5': 'Identificación de Policía Ministerial, Judicial o de Investigación. Otro',
 'AP5_8_06_1': 'Identificación de Ministerio Público (MP) y Fiscalías Estatales por contacto directo.',
 'AP5_8_06_2': 'Identificación de Ministerio Público (MP) y Fiscalías Estatales porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_06_3': 'Identificación de Ministerio Público (MP) y Fiscalías Estatales porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_06_4': 'Identificación de Ministerio Público (MP) y Fiscalías Estatales porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_06_5': 'Identificación de Ministerio Público (MP) y Fiscalías Estatales. Otro',
 'AP5_8_07_1': 'Identificación de Fiscalía General de la República (FGR) por contacto directo.',
 'AP5_8_07_2': 'Identificación de Fiscalía General de la República (FGR) porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_07_3': 'Identificación de Fiscalía General de la República (FGR) porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_07_4': 'Identificación de Fiscalía General de la República (FGR) porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_07_5': 'Identificación de Fiscalía General de la República (FGR). Otro',
 'AP5_8_08_1': 'Identificación de Ejército por contacto directo.',
 'AP5_8_08_2': 'Identificación de Ejército porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_08_3': 'Identificación de Ejército porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_08_4': 'Identificación de Ejército porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_08_5': 'Identificación de Ejército. Otro',
 'AP5_8_09_1': 'Identificación de Fuerza Aérea Mexicana por contacto directo.',
 'AP5_8_09_2': 'Identificación de Fuerza Aérea Mexicana porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_09_3': 'Identificación de Fuerza Aérea Mexicana porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_09_4': 'Identificación de Fuerza Aérea Mexicana porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_09_5': 'Identificación de Fuerza Aérea Mexicana. Otro',
 'AP5_8_10_1': 'Identificación de Marina por contacto directo.',
 'AP5_8_10_2': 'Identificación de Marina porque ha visto a esa autoridad en la calle o vía pública.',
 'AP5_8_10_3': 'Identificación de Marina porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_10_4': 'Identificación de Marina porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_10_5': 'Identificación de Marina. Otro',
 'AP5_8_11_1': 'Identificación de Jueces por contacto directo.',
 'AP5_8_11_3': 'Identificación de Jueces porque le han platicado de esa autoridad familiares vecinos(as) o amigos(as).',
 'AP5_8_11_4': 'Identificación de Jueces porque ha leído, visto o escuchado de esa autoridad en medios de comunicación o en internet.',
 'AP5_8_11_5': 'Identificación de Jueces. Otro',
 'AP5_9': 'Confianza en cárceles y reclusorios',
 'FAC_HOG': 'Factor hogar',
 'FAC_ELE': 'Factor de personas elegidas',
 'FAC_HOG_AM': 'Factor hogar del área urbana de interés',
 'FAC_ELE_AM': 'Factor de personas elegidas del área urbana de interés',
 'DOMINIO': 'Dominio',
 'ESTRATO': 'Estrato sociodemográfico',
 'EST_DIS': 'Estrato de diseño muestral',
 'UPM_DIS': 'Unidad primaria de muestreo'}

### Preprocessing

In [7]:
df_envipe["muni_id"] = df_envipe["CVE_ENT"] + df_envipe["CVE_MUN"]
df_envipe.head()

,ID_VIV,ID_HOG,ID_PER,UPM,VIV_SEL,HOGAR,RESUL_H,R_SEL,SEXO,EDAD,...,AP5_9,FAC_HOG,FAC_ELE,FAC_HOG_AM,FAC_ELE_AM,DOMINIO,ESTRATO,EST_DIS,UPM_DIS,muni_id
0,100107.01,0100107.01.01,0100107.01.01.01,100107,1,1,B,1,2,56,...,3,241,241,241.0,241.0,U,2,1,47,01001
1,100107.02,0100107.02.01,0100107.02.01.02,100107,2,1,A,2,2,30,...,2,241,482,241.0,482.0,U,2,1,47,01001
2,100107.03,0100107.03.01,0100107.03.01.04,100107,3,1,B,4,2,18,...,9,241,963,241.0,963.0,U,2,1,47,01001
3,100107.04,0100107.04.01,0100107.04.01.03,100107,4,1,A,3,1,22,...,2,241,723,241.0,723.0,U,2,1,47,01001
4,100107.05,0100107.05.01,0100107.05.01.01,100107,5,1,B,1,2,36,...,2,241,482,241.0,482.0,U,2,1,47,01001

In [8]:
df_envipe = df_envipe[df_envipe.CVE_ENT.isin(['12', '16', '15'])]
df_envipe.NOM_ENT.unique()

array(['GUERRERO', 'MEXICO', 'MICHOACAN DE OCAMPO'], dtype=object)

### Collusion index

**a) Perception of security & local crime environment**

* AP4_3_2 – Percepción sobre seguridad en su municipio o demarcación territorial
* AP4_5_15 – Incivilidades en su colonia: extorsiones (cobro de piso)
* AP4_5_16 – Incivilidades en su colonia: robo o venta ilegal de gasolina o diésel (huachicol)

**b) Trust & perceived corruption in authorities**

Municipal police:
* AP5_4_02 – Confianza en Policía Preventiva Municipal
* AP5_5_02 – Percepción sobre corrupción de Policía Preventiva Municipal
* AP5_6_02 – Percepción sobre desempeño de Policía Preventiva Municipal

State police:
* AP5_4_03 – Confianza en Policía Estatal
* AP5_5_03 – Percepción sobre corrupción de Policía Estatal
* AP5_6_03 – Percepción sobre desempeño de Policía Estatal

In [9]:
id_cols = ['CVE_ENT', 'NOM_ENT', 'muni_id', 'NOM_MUN']
weights = ['FAC_PER']  # personal-level weight
sec_per = ['AP4_3_2']
trust_per = ['AP5_4_02', 'AP5_4_03']
corr_per = ['AP5_5_02', 'AP5_5_03']
perf_per = ['AP5_6_02', 'AP5_6_03']

In [10]:
# 1) Insecurity in municipality (AP4_3_2)
sec_map = {1: 0.0,  # seguro
           2: 1.0}  # inseguro

df_envipe["insecurity_mun"] = df_envipe["AP4_3_2"].map(sec_map)

# 2) Trust in municipal & state police
trust_map = {
    1: 1.0,   # mucha confianza
    2: 2/3,   # algo de confianza
    3: 1/3,   # algo de desconfianza
    4: 0.0    # mucha desconfianza
}

for col in trust_per:
    df_envipe[f"trust_{col}"] = df_envipe[col].map(trust_map)

# Average trust across municipality + state police
df_envipe["trust_police"] = df_envipe[[f"trust_{c}" for c in trust_per]].mean(axis=1)

# Turn into mistrust (0=trust, 1=mistrust)
df_envipe["mistrust_police"] = 1 - df_envipe["trust_police"]

# 3) Perceived corruption (yes/no)
corr_map = {
    1: 1.0,  # Sí son corruptos
    2: 0.0   # No
}

for col in corr_per:
    df_envipe[f"corr_{col}"] = df_envipe[col].map(corr_map)

df_envipe["corr_police"] = df_envipe[[f"corr_{c}" for c in corr_per]].mean(axis=1)

# 4) Performance → ineffectiveness
ineff_map = {
    1: 0.0,  # muy efectivo
    2: 1/3,
    3: 2/3,
    4: 1.0  # nada efectivo
}

for col in perf_per:
    df_envipe[f"ineff_{col}"] = df_envipe[col].map(ineff_map)

df_envipe["ineff_police"] = df_envipe[[f"ineff_{c}" for c in perf_per]].mean(axis=1)

In [11]:
df_envipe.head()

,ID_VIV,ID_HOG,ID_PER,UPM,VIV_SEL,HOGAR,RESUL_H,R_SEL,SEXO,EDAD,...,trust_AP5_4_02,trust_AP5_4_03,trust_police,mistrust_police,corr_AP5_5_02,corr_AP5_5_03,corr_police,ineff_AP5_6_02,ineff_AP5_6_03,ineff_police
33100,1200174.03,1200174.03.01,1200174.03.01.01,1200174,3,1,B,1,2,67,...,0.666667,0.666667,0.666667,0.333333,1.0,1.0,1.0,0.666667,0.666667,0.666667
33101,1200174.04,1200174.04.01,1200174.04.01.04,1200174,4,1,A,4,1,50,...,0.666667,0.666667,0.666667,0.333333,1.0,1.0,1.0,0.333333,0.333333,0.333333
33102,1200177.01,1200177.01.01,1200177.01.01.01,1200177,1,1,B,1,2,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33103,1200177.02,1200177.02.01,1200177.02.01.02,1200177,2,1,A,2,1,38,...,0.000000,0.000000,0.000000,1.000000,1.0,1.0,1.0,0.666667,0.666667,0.666667
33104,1200177.03,1200177.03.01,1200177.03.01.01,1200177,3,1,B,1,2,77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
def wavg(series, weights):
    mask = (~series.isna()) & (~weights.isna())
    if mask.sum() == 0:
        return np.nan
    return np.average(series[mask], weights=weights[mask])

envipe_mun = (
    df_envipe.groupby(id_cols)
      .apply(lambda g: pd.Series({
          "insecurity_mun":  wavg(g["insecurity_mun"],  g["FAC_ELE"]),
          "mistrust_police": wavg(g["mistrust_police"], g["FAC_ELE"]),
          "corr_police":     wavg(g["corr_police"],     g["FAC_ELE"]),
          "ineff_police":    wavg(g["ineff_police"],    g["FAC_ELE"]),
      }))
      .reset_index()
)

C:\Users\penny\AppData\Local\Temp\ipykernel_8728\1095217559.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

In [13]:
s = (
    0.35 * envipe_mun["corr_police"] +
    0.25 * envipe_mun["mistrust_police"] +
    0.20 * envipe_mun["ineff_police"] +
    0.20 * envipe_mun["insecurity_mun"]
)

envipe_mun["collusion_idx_raw"] = s
envipe_mun["collusion_idx"] = ((s - s.min()) / (s.max() - s.min()))

In [14]:
envipe_mun.head()

,CVE_ENT,NOM_ENT,muni_id,NOM_MUN,insecurity_mun,mistrust_police,corr_police,ineff_police,collusion_idx_raw,collusion_idx
0,12,GUERRERO,12001,ACAPULCO DE JUAREZ,0.891895,0.614207,0.773391,0.604499,0.723517,0.783212
1,12,GUERRERO,12003,AJUCHITLAN DEL PROGRESO,0.558824,0.333333,0.769231,0.566667,0.577662,0.572155
2,12,GUERRERO,12006,APAXTLA,0.272689,0.298229,0.708343,0.429791,0.462973,0.406196
3,12,GUERRERO,12007,ARCELIA,0.332788,0.380682,0.426025,0.382584,0.387353,0.296772
4,12,GUERRERO,12010,ATLIXTAC,0.500039,0.484122,0.342120,0.460336,0.432848,0.362603

In [15]:
envipe_mun.columns = envipe_mun.columns.str.lower()
envipe_mun.rename(columns={'cve_ent': 'state_id', 'nom_ent': 'state',  
                          'nom_mun': 'municipality'}, inplace=True)

envipe_mun['year'] = 2025
envipe_mun['year'] = envipe_mun['year'].astype('int64')
envipe_mun['state_id'] = envipe_mun['state_id'].astype('int64')
envipe_mun['state'] = envipe_mun['state'].astype('str')
envipe_mun['muni_id'] = envipe_mun['muni_id'].astype('str')
envipe_mun['municipality'] = envipe_mun['municipality'].astype('str')

In [16]:
print(envipe_mun.shape)
envipe_mun.head(10)

(163, 11)

,state_id,state,muni_id,municipality,insecurity_mun,mistrust_police,corr_police,ineff_police,collusion_idx_raw,collusion_idx,year
0,12,GUERRERO,12001,ACAPULCO DE JUAREZ,0.891895,0.614207,0.773391,0.604499,0.723517,0.783212,2025
1,12,GUERRERO,12003,AJUCHITLAN DEL PROGRESO,0.558824,0.333333,0.769231,0.566667,0.577662,0.572155,2025
2,12,GUERRERO,12006,APAXTLA,0.272689,0.298229,0.708343,0.429791,0.462973,0.406196,2025
3,12,GUERRERO,12007,ARCELIA,0.332788,0.380682,0.426025,0.382584,0.387353,0.296772,2025
4,12,GUERRERO,12010,ATLIXTAC,0.500039,0.484122,0.342120,0.460336,0.432848,0.362603,2025
5,12,GUERRERO,12011,ATOYAC DE ALVAREZ,0.427127,0.365157,0.503886,0.402423,0.433559,0.363633,2025
6,12,GUERRERO,12012,AYUTLA DE LOS LIBRES,0.818782,0.458868,0.444611,0.485167,0.531121,0.504807,2025
7,12,GUERRERO,12019,COPALILLO,0.611446,0.443592,0.518358,0.494558,0.513524,0.479345,2025
8,12,GUERRERO,12020,COPANATOYAC,0.625429,0.500244,0.533988,0.566435,0.550330,0.532603,2025
9,12,GUERRERO,12021,COYUCA DE BENITEZ,0.688688,0.490717,0.520528,0.462088,0.535019,0.510449,2025

#### Save data

In [18]:
envipe_mun.to_csv(out_collusion_panel, index=False)